package com.jd.spring;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library' by
 * 'ManhHoang' at '6/3/16 11:40 AM' with Gradle 2.13
 * 
 * @author ManhHoang, @date 6/3/16 11:40 AM
 */
public class LibraryTest {

  @Test
  public void testSomeLibraryMethod() {
    Library classUnderTest = new Library();
    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
  }
}
