package com.jd.spring;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library' by
 * 'ManhHoang' at '6/3/16 11:40 AM' with Gradle 2.13
 * 
 * @author ManhHoang, @date 6/3/16 11:40 AM
 */
public class Library {
  public boolean someLibraryMethod() {
    return true;
  }
}
